CREATE DATABASE mydatabase;

USE mydatabase;

CREATE TABLE users (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(30) NOT NULL,
  prenom VARCHAR(30) NOT NULL,
  email VARCHAR(50),
  contact VARCHAR(20),
  section VARCHAR(30)
);